#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}

branches:
  only:
    - master
    - test-ci

#---------------------------------#
#    environment configuration    #
#---------------------------------#

os: Windows Driver Kit 10

platform:
  - x86

build_script:
  - .\tools\make-win64-dev-env.bat
  - .\tools\make-win64-binaries.bat